# based on https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

name: Upload SBOM to EdgeBit

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Download metadata
        id: metadata
        uses: actions/download-artifact@v4-beta
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: metadata.json

      - name: Download SBOM
        id: sbom
        uses: actions/download-artifact@v4-beta
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: edgebit-agent.spdx.json

      - name: Upload SBOM to EdgeBit
        uses: edgebitio/edgebit-build@v1
        with:
          edgebit-url: https://edgebit.edgebit.io
          token: ${{ secrets.EDGEBIT_TOKEN }}
          component: edgebitio-edgebit-agent
          sbom-file: ${{ steps.sbom.outputs.download-path }}
          args-file: ${{ steps.metadata.outputs.download-path }}
